# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Wooil-Land CI/CD

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Action Secret
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and release to DockerHub
      env:
        NAME: ba91
        REPO: wooil-land-server
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
  deploy:
    needs: build
    name: depoly
    runs-on: self-hosted
    steps:
      - name: docker restart
        run: |
          docker ps -q --filter "name=wooil-land-backend" | grep -q . && docker stop "wooil-land-backend" && docker rm wooil-land-backend && docker rmi ba91/wooil-land-server
          docker run -d --name wooil-land-backend -p 8080:8080 ba91/wooil-land-server